# 服务器环境配置
server:
  port: 8100

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://47.106.36.36:3306/dango?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MySQL123!@#

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dango.core.dao
  configuration:
    # 下划线风格映射到驼峰命名（便于数据库字段映射到 java 对象属性）
    map-underscore-to-camel-case: true

# log 配置
logging:
  level:
    # mybatis 日志级别为 debug
    com.dango.core.dao: debug
    com.dango.common.util: debug
